### ISSUE TITLE
Voltage source not respecting parameter frequency ?

### ISSUE THREAD

**Issue by prhyland** [modelica/PowerSystems#36]
I tried to use 2 voltage sources of same amplitude but set at different frequencies (50 and 51 Hz) to oscillate  power across a connecting impedance at the beat frequency. Voltage sources I used were from AC3ph.Sources.Voltage. However both voltages calculated identically across time (therefore no current between them). Digging into the code, the Voltage source did not use the calculated theta from the frequency (fType = parameter).

The line in question in Sources.mo for model Voltage is

    phi = term.theta[1] + alpha + system.alpha0;
    term.v = PS.map({V*cos(phi), V*sin(phi), sqrt(3)*neutral.v});

However, term.theta[1] appears always set to system.thetaRel (set in partial SourceBase). Whilst theta for the Voltage instance is calculated correctly (in partial VoltageBase), it seems as if it is never used.

My model worked when I changed the library line to:

    phi = (theta - system.thetaRef) + alpha + system.alpha0;

that is, calculating the angle of the voltage source instance relative to the reference frame.

Fixing it here does not seem right though - term.theta should be changed?? However, line elements connect theta through (term_p.theta = term_n.theta) so you would end up with an over-defined system or one that cannot be solved.

As it stands, term.theta seems a bit useless as it can only be = {system.thetaRel, system.thetaRef}. Or am I missing something? It would seem to me more intuitive if each active element's term.theta referred to its actual relative angle to the reference frame and passive elements did not pass it through. In any regard, the Voltage source appears to have a fixable bug as it currently does not respect the frequency parameter.

I am pretty new to this so sorry if I have missed something fundamental or some setting somewhere.

**Comment by rfranke** [comment]
Sorry for the late reply. The `AC3ph` components use `PhaseSystems.ThreePhase_dq0`. The common reference frame is passed through `term.theta` to all interconnected simulation model -- enabling the treatment of transient effects.

You cannot connect subsystems with different frequency through an impedance, because the impedance model assumes the same reference frame on both of its ports.

You need to explicitly decouble sub-systems with different frequencies, e.g. using inverters. See `PowerSystems.Examples.Wind.WindTurbine_*` models showing combinations of inverters and asynchronous machines to support variable frequencies.

Alternatively, you might try the `AC1ph_DC` components. Have a look at `PowerSystems.Examples.AC1ph_DC.Elementary.Line`. There you can define 50 and 51 Hz in the two sources, along with fType Parameter, and simulate in the time domain.
